id: IEE4DD5DD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T00:15:24+00:00'
last_modified: '2022-06-07T17:24:31.132564+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4744
  title: འདུལ་བ་འོད་ལྡན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8112':
      image_group_id: I3CN4746
      title: ''
      total_pages: 204
      order: 1
      base_file: 8112.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
