id: P003077
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:38:55.762684
source_metadata:
  id: bdr:W3CN4744
  title: འདུལ་བ་འོད་ལྡན།
  author: ''
  volumes:
    954b9f4684eb4402ab4de71a7e147824:
      image_group_id: I3CN4746
      title: ''
      volume_number: 1
      total_pages: 204
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
